const MOBILE_SET = 1
const MOBILE_VERIFIED = 2
const TRANSACTION_PASSWORD_SET = 4
const SECURITY_QUESTIONS_SET = 8
const IDENTITY_SET = 16
const IDENTITY_TAKEN = 32
const CHECK_GONGAN = 64
const IDENTITY_VERIFIED = 128
const CHECK_IMAGES_STATUS = 256
const CHECK_ACCOUNT_TYPE = 512

export {
  MOBILE_SET,
  MOBILE_VERIFIED,
  TRANSACTION_PASSWORD_SET,
  SECURITY_QUESTIONS_SET,
  IDENTITY_SET,
  IDENTITY_TAKEN,
  CHECK_GONGAN,
  IDENTITY_VERIFIED,
  CHECK_IMAGES_STATUS,
  CHECK_ACCOUNT_TYPE
}
